const favoriteTGs = [
    {"name":"World-wide","category":"International","ID":91},
    {"name":"North America","category":"International","ID":93},
    {"name":"Australia, New Zealand","category":"International","ID":95},
    {"name":"United Kingdom","category":"International","ID":235},
    {"name":"Canada","category":"International","ID":302},
    {"name":"TAC-310 USA DMRX Bridge","category":"National","ID":310},
    {"name":"TAC-311 USA DMRX Bridge","category":"National","ID":311},
    {"name":"TAC-312 USA DMRX Bridge","category":"National","ID":312},
    {"name":"TAC-313 USA","category":"National","ID":313},
    {"name":"TAC-314 USA","category":"National","ID":314},
    {"name":"TAC-315 USA","category":"National","ID":315},
    {"name":"TAC-316 USA","category":"National","ID":316},
    {"name":"TAC-317 USA","category":"National","ID":317},
    {"name":"TAC-318 USA","category":"National","ID":318},
    {"name":"TAC-319 USA","category":"National","ID":319},
    {"name":"Israel","category":"International","ID":425},
    {"name":"Nationwide","category":"National","ID":3100},
    {"name":"Alabama","category":"Alabama","ID":3101,"static":true},
    {"name":"Arkansas","category":"States","ID":3105},
    {"name":"DC","category":"States","ID":3111},
    {"name":"Georgia","category":"States","ID":3113},
    {"name":"Kansas","category":"States","ID":3120,"static":true},
    {"name":"Mississippi","category":"States","ID":3128,"static":true},
    {"name":"Missouri","category":"States","ID":3129},
    {"name":"Tennessee","category":"States","ID":3147,"static":true},
    {"name":"Virginia","category":"States","ID":3151},
    {"name":"Southeast","category":"Regional","ID":3174},
    {"name":"Missouri Lakes","category":"Cities","ID":3180},
    {"name":"United Kingdom","category":"International","ID":4400},
    {"name":"Alabama Link","category":"Alabama","ID":31010},
    {"name":"Gulf Coast DMR","category":"Alabama","ID":31011},
    {"name":"QuadNet","category":"Alabama","ID":31012},
    {"name":"Alert-K4NWS","category":"Alabama","ID":31013,"static":true},    
    {"name":"HSV","category":"Alabama","ID":31014,"static":true},
    {"name":"Central Alabama","category":"Alabama","ID":31015,"static":true},
    {"name":"NW Alabama","category":"Alabama","ID":31016,"static":true},
    {"name":"Southern California","category":"Cities","ID":31066},
    {"name":"BayNet","category":"Cities","ID":31075},
    {"name":"Atlanta Metro","category":"Cities","ID":31131},
    {"name":"BYRG (KC)","category":"Cities","ID":31201,"static":true},
    {"name":"BYRG2 (KC)","category":"Cities","ID":31202},
    {"name":"Kansas Link","category":"States","ID":31203},
    {"name":"KC Skywarn","category":"Cities","ID":31205},
    {"name":"Corinth Local","category":"Cities","ID":31285},
    {"name":"SW Missouri","category":"Cities","ID":31291},
    {"name":"STL Metro","category":"Cities","ID":31292},
    {"name":"NW Missouri","category":"Cities","ID":31294},
    {"name":"Central Missouri","category":"Cities","ID":31296},
    {"name":"NY Metro","category":"Cities","ID":31362},
    {"name":"Carolina Link","category":"States","ID":31374},
    {"name":"Mid-South Chat","category":"Cities","ID":31470,"static":true},
    {"name":"The Light","category":"Other/Topics","ID":31479,"static":true},
    {"name":"USA - 4","category":"Regional","ID":31604},
    {"name":"DMR Info","category":"Other/Topics","ID":31648},
    {"name":"America Link","category":"National","ID":31656},
    {"name":"PI-Star Chat","category":"Other/Topics","ID":31672},
    {"name":"Gigaparts","category":"Other/Topics","ID":31695,"static":false},
    {"name":"Liberty","category":"Other/Topics","ID":31776,"static":false},
    {"name":"Sheffield Local","category":"Alabama","ID":310128},
    {"name":"Jonesboro Local","category":"Cities","ID":310514,"static":true},
    {"name":"Memphis Local","category":"Cities","ID":314706},
    {"name":"Reddit","category":"Other/Topics","ID":98003},
    {"name":"AE4G","category":"Personal TG","ID":3138607},
    {"name":"AB4CD","category":"Personal TG","ID":3138700}

];

export default favoriteTGs;