const favoriteTGs = [
    {"name":"World-wide","category":"International","ID":91},
    {"name":"North America","category":"International","ID":93},
    {"name":"Australia, New Zealand","category":"International","ID":95},
    {"name":"United Kingdom","category":"International","ID":235},
    {"name":"Canada","category":"International","ID":302},
    {"name":"TAC-310 USA DMRX Bridge","category":"National","ID":310},
    {"name":"TAC-311 USA DMRX Bridge","category":"National","ID":311},
    {"name":"TAC-312 USA DMRX Bridge","category":"National","ID":312},
    {"name":"Alabama","category":"Alabama","ID":3101},
    {"name":"Kansas","category":"States","ID":3120},
    {"name":"Missouri","category":"States","ID":3129},
    {"name":"Tennessee","category":"States","ID":3147},
    {"name":"Southeast","category":"Regional","ID":3174},
    {"name":"United Kingdom","category":"International","ID":4400},
    {"name":"Alabama Link","category":"Alabama","ID":31010},
    {"name":"Gulf Coast DMR","category":"Alabama","ID":31011},
    {"name":"QuadNet","category":"Alabama","ID":31012},
    {"name":"Alert-K4NWS","category":"Alabama","ID":31013},    
    {"name":"HSV","category":"Alabama","ID":31014},
    {"name":"Central Alabama","category":"Alabama","ID":31015},
    {"name":"NW Alabama","category":"Alabama","ID":31016},
    {"name":"BayNet","category":"Cities","ID":31075},
    {"name":"Atlanta Metro","category":"Cities","ID":31131},
    {"name":"BYRG (KC)","category":"Cities","ID":31201},
    {"name":"KC Skywarn","category":"Cities","ID":31205},
    {"name":"Mid-South Chat","category":"Cities","ID":31470},
    {"name":"The Light","category":"Other/Topics","ID":31479},
    {"name":"PI-Star Chat","category":"Other/Topics","ID":31672},
    {"name":"Gigaparts","category":"Other/Topics","ID":31695},
    {"name":"Reddit","category":"Other/Topics","ID":98003}
];

export default favoriteTGs;