const repeaters = [
    {"name":"Huntsville","call":"W4FMX","category":"North AL","ID":310112},
    {"name":"Somerville","call":"WR4JW","category":"North AL","ID":310357},
    {"name":"Cullman","call":"N4UAI","category":"North AL","ID":310127},
    {"name":"Sheffield","call":"N4GLE","category":"North AL","ID":310128},
    {"name":"Alabaster","call":"N4FIV","category":"Central AL","ID":310104},
    {"name":"Red Mtn","call":"KA5GET","category":"Central AL","ID":310177},
    {"name":"Helena","call":"KC4SIG","category":"Central AL","ID":310117},
    {"name":"Trussville","call":"KC4ANB","category":"Central AL","ID":310120},
    {"name":"Fayette","call":"KK4QXR","category":"Central AL","ID":310110},
    {"name":"Auburn","call":"N4NQV","category":"Central AL","ID":310124},
    {"name":"Corinth, MS","call":"K5WHB","category":"West","ID":312804},
    {"name":"Memphis, TN","call":"W4LET","category":"West","ID":314706},
    {"name":"Jonesboro, AR","call":"NZ5E","category":"West","ID":310514},
    {"name":"Springfield, MO","call":"K0NXA","category":"BYRG","ID":312919},
    {"name":"Boliver, MO","call":"WB0LVR","category":"BYRG","ID":312924},
    {"name":"Deepwater, MO","call":"W0DR","category":"BYRG","ID":312936},
    {"name":"KC, MO","call":"WB0YRG","category":"BYRG","ID":312906},
    {"name":"Mission, KS","call":"WB0YRG-1","category":"BYRG","ID":312010},
    {"name":"KCI Airport","call":"WB0YRG-2","category":"BYRG","ID":312932},
    {"name":"Independence, MO","call":"WB0YRG-3","category":"BYRG","ID":312907},
    {"name":"Peculiar, MO","call":"WB0YRG-4","category":"BYRG","ID":312910},
];

export default repeaters;