const repeaters = [
    {"name":"Huntsville","call":"W4FMX","category":"Home","ID":310112},
    {"name":"Somerville","call":"WR4JW","category":"Home","ID":310357},
    {"name":"Cullman","call":"N4UAI","category":"Home","ID":310127},
    {"name":"Sheffield","call":"N4GLE","category":"Home","ID":310128},
    {"name":"Alabaster","call":"N4FIV","category":"Home","ID":310104},
    {"name":"Red Mtn","call":"KA5GET","category":"Home","ID":310177},
    {"name":"Helena","call":"KC4SIG","category":"Home","ID":310117},
    {"name":"Trussville","call":"KC4ANB","category":"Home","ID":310120},
    {"name":"Nashville","call":"NE4MA","category":"Home","ID":311179},
    {"name":"Corinth, MS","call":"K5WHB","category":"KC","ID":312802},
    {"name":"Memphis, TN","call":"W4LET","category":"KC","ID":314706},
    {"name":"Jonesboro, AR","call":"NZ5E","category":"KC","ID":310514},
    {"name":"Springfield, MO","call":"K0NXA","category":"KC","ID":312919},
    {"name":"Boliver, MO","call":"WB0LVR","category":"KC","ID":312924},
    {"name":"Deepwater, MO","call":"W0DR","category":"KC","ID":312936},
    {"name":"KC, MO","call":"WB0YRG","category":"KC","ID":312906},
    {"name":"Mission, KS","call":"WB0YRG-1","category":"KC","ID":312010},
    {"name":"KCI Airport","call":"WB0YRG-2","category":"KC","ID":312932},
    {"name":"Independence, MO","call":"WB0YRG-3","category":"KC","ID":312907},
    {"name":"Peculiar, MO","call":"WB0YRG-4","category":"KC","ID":312910},
    {"name":"Springfield, TN","call":"AD4RM","category":"WI","ID":311354},
    {"name":"Bowling Green, KY","call":"W4WSM","category":"WI","ID":312117},
    {"name":"Elizabethtown, KY","call":"KG4LHQ","category":"WI","ID":312107},
    {"name":"Indianapolis, IN","call":"W9AMT","category":"WI","ID":311845},
    {"name":"West Lafayette, IN","call":"W9YB","category":"WI","ID":311822},
    {"name":"Winthrop Harbor, IL","call":"KD9MDL","category":"WI","ID":3123647}
];

export default repeaters;